reference_latitude: 15.4507
reference_longitude: 73.8041

gps_port: "/tmp/gps-read"
gps_baudrate: B9600
gps_status: 1

ahrs_port: "/tmp/ahrs-read"
ahrs_baudrate: B115200
ahrs_status: 1

thrusters_port: "/tmp/thr-write"
thrusters_baudrate: B9600

guidance_on: 1
thrusters_on: 1

mode: "AUV"
status: "Drive"